Oleh Roikhatul Miskiyah - PYTN-KS05-010 - Batch 5

# NumPy

In [1]:
import numpy as np

## Terminology

In [4]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [5]:
print(a[0])

[1 2 3 4]


## Array

In [7]:
a = np.array([1,2,3,4])

In [8]:
a

array([1, 2, 3, 4])

In [9]:
# mengisi array dg nilai 0
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
# mengisi array dg nilai 1
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
# mengisi array dg nilai random
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
print(np.arange(4))

[0 1 2 3]


In [15]:
print(np.arange(0,10,3)) #start, stop, step

[0 3 6 9]


## Add, Remove, and Sort

In [16]:
arr = np.array([1,2,3,4,5,6,7,8])

In [17]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [18]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [19]:
arr = np.array([10,2,13,14,5,16,7,8])

In [20]:
np.sort(arr)

array([ 2,  5,  7,  8, 10, 13, 14, 16])

## Shape dan Size

In [21]:
# ndim untuk mengetahui jml axes/ dimensi
# size untuk mengetahui jml total elemen array
# shape untuk menampilkan tuple integer

In [22]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7,]],
                          [[0,1,2,3,],
                           [4,5,6,7]],
                          [[0,1,2,3],
                           [4,5,6,7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [23]:
array_example.ndim

3

In [24]:
array_example.size

24

In [25]:
array_example.shape

(3, 2, 4)

In [26]:
arr_one = np.array([[1,2,3,4,5]])

In [27]:
arr_one.ndim

2

In [28]:
arr_one.size

5

In [29]:
arr_one.shape

(1, 5)

## Reshape

In [30]:
# untuk memberikan bentuk baru ke array tanpa mengubah datanya
a = np.arange(6)

In [31]:
print(a)

[0 1 2 3 4 5]


In [33]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [35]:
# np.newaxis dan np.expand_dims untuk meningkatkan dimensi array yang sudah ada
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [37]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [38]:
# bisa menambahkan axis di dimensi pertama (untuk baris)
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [39]:
# untuk vektor kolom, dapat menambahkan axis dengan 2 dimensi
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [40]:
# memperluas array 
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [41]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [42]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing 

In [43]:
data = np.array([1,2,3])

In [45]:
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [46]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
# mencetak nilai yang lebih dari 5
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [50]:
five_up = (a >= 5)
print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [51]:
# memilih elemen yang bisa dibagi 2
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [52]:
c = a[(a > 2) & (a<11)]

In [53]:
print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [54]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [56]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [57]:
a_1 = np.array([[1,1],
               [2,2]])

In [60]:
a_2 = np.array([[3,3],
               [4,4]])

In [61]:
np.vstack((a_1, a_2))

array([[3, 3],
       [4, 4],
       [3, 3],
       [4, 4]])

In [63]:
np.hstack((a_1, a_2))

array([[3, 3, 3, 3],
       [4, 4, 4, 4]])

In [66]:
arrsplit = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [67]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [69]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic array operations

In [73]:
a = np.array([1,2,3,4])
a.sum()

10

In [76]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [77]:
b.sum(axis=0)

array([3, 3])

In [78]:
b.sum(axis=1)

array([2, 4])

In [80]:
data = np.array([1,2])
data

array([1, 2])

In [81]:
ones = np.ones(2)
ones

array([1., 1.])

In [82]:
data + ones

array([2., 3.])

In [83]:
data * data

array([1, 4])

In [84]:
data / data

array([1., 1.])

## Broadcasting

In [85]:
data * 2

array([2, 4])

## More Array Operations

In [89]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [90]:
A.sum()

4.8595784

In [91]:
A.min()

0.05093587

In [92]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [93]:
A.max()

0.82485143

In [94]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [95]:
A.std()

0.21392120766089617

## Matrices

In [96]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.52001581, 0.67346446],
       [0.19398495, 0.88723555],
       [0.45962279, 0.95800568]])

In [97]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.63538995 0.32631145]
 [0.19604691 0.82188048]
 [0.30143887 0.62260496]]


## Matrix Arithmetic

In [99]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [101]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [102]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [104]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [105]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [106]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [107]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [108]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [109]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [110]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [111]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [112]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [113]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [114]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [115]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [117]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [118]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [119]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [122]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [123]:
print(np.random.random((4,3,2)))

[[[0.45825005 0.85247394]
  [0.14530071 0.66651255]
  [0.87046912 0.06484409]]

 [[0.14323763 0.6908974 ]
  [0.52536655 0.0745068 ]
  [0.10063086 0.95064504]]

 [[0.3742642  0.80675861]
  [0.59587303 0.23401015]
  [0.10461182 0.53076059]]

 [[0.70200007 0.99750444]
  [0.39379253 0.95248954]
  [0.03912548 0.40003123]]]


## Flatten N-Dimensional Array

In [124]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [125]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas